# Generated by Django 3.2.9 on 2021-12-07 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20211205_1545'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('title', 'slug')},
        ),
    ]
